# Generated by Django 2.1.7 on 2019-03-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_links',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
